-- Phase 1 schema: teams, users, contacts, meetings, meeting_invitees.
-- Primary keys are UUIDs generated by the application (java-uuid-generator, v7) —
-- no DB-side default, the app always sets the id before insert.

CREATE TABLE teams (
    id         UUID PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    slug       VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_teams_slug UNIQUE (slug)
);

CREATE TABLE users (
    id              UUID PRIMARY KEY,
    email           VARCHAR(255) NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    full_name       VARCHAR(160) NOT NULL,
    timezone        VARCHAR(64) NOT NULL DEFAULT 'UTC',
    role            VARCHAR(32) NOT NULL DEFAULT 'member',
    team_id         UUID NOT NULL REFERENCES teams (id),
    created_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX ix_users_team_id ON users (team_id);

CREATE TABLE contacts (
    id         UUID PRIMARY KEY,
    team_id    UUID NOT NULL REFERENCES teams (id),
    name       VARCHAR(160) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    company    VARCHAR(160),
    phone      VARCHAR(40),
    title      VARCHAR(120),
    notes      TEXT,
    stage      VARCHAR(40) NOT NULL DEFAULT 'lead',
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX ix_contacts_team_id ON contacts (team_id);
CREATE INDEX ix_contacts_email ON contacts (email);

CREATE TABLE meetings (
    id                UUID PRIMARY KEY,
    team_id           UUID NOT NULL REFERENCES teams (id),
    host_id           UUID NOT NULL REFERENCES users (id),
    title             VARCHAR(200) NOT NULL,
    notes             TEXT,
    start_time        TIMESTAMPTZ NOT NULL,
    end_time          TIMESTAMPTZ NOT NULL,
    meeting_timezone  VARCHAR(64) NOT NULL DEFAULT 'UTC',
    status            VARCHAR(32) NOT NULL DEFAULT 'scheduled',
    created_at        TIMESTAMPTZ NOT NULL
);

CREATE INDEX ix_meetings_team_id ON meetings (team_id);
CREATE INDEX ix_meetings_host_id ON meetings (host_id);
CREATE INDEX ix_meetings_start_time ON meetings (start_time);

CREATE TABLE meeting_invitees (
    id         UUID PRIMARY KEY,
    meeting_id UUID NOT NULL REFERENCES meetings (id) ON DELETE CASCADE,
    contact_id UUID NOT NULL REFERENCES contacts (id),
    response   VARCHAR(32) NOT NULL DEFAULT 'pending'
);

CREATE INDEX ix_meeting_invitees_meeting_id ON meeting_invitees (meeting_id);
CREATE INDEX ix_meeting_invitees_contact_id ON meeting_invitees (contact_id);
